import cv2
img = cv2.imread("Rc2026.jpg", 0)
kernel_rect = cv2.getStructuringElement(cv2.MORPH_RECT, (7,7))
kernel_ellipse = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7,7))
kernel_cross = cv2.getStructuringElement(cv2.MORPH_CROSS, (7,7))
rect = cv2.erode(img, kernel_rect)
ellipse = cv2.erode(img, kernel_ellipse)
cross = cv2.erode(img, kernel_cross)
cv2.imshow("Rect Kernel", rect)
cv2.imshow("Ellipse Kernel", ellipse)
cv2.imshow("Cross Kernel", cross)
cv2.waitKey(0)
cv2.destroyAllWindows()
